# for creating these resources it requires the user to be logged in as system admin
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${artifactId}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ${artifactId}-edit-resources
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
subjects:
  - kind: ServiceAccount
    name: ${artifactId}
    namespace: myproject
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ${artifactId}
  labels: &default-labels
    app.kubernetes.io/name: ${artifactId}
    app.kubernetes.io/version: v0.0.1-v1alpha1
spec:
  replicas: 1
  selector:
    matchLabels: *default-labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels: *default-labels
    spec:
      serviceAccountName: ${artifactId}
      containers:
      - name: ${artifactId}
        image: ${groupId}/${artifactId}:latest
        env:
        - name: CRD
          value: "true"
        imagePullPolicy: IfNotPresent

